### PR TITLE
Fix/add other dds vendors

### PR DESCRIPTION
**Pull request by Guillaumebeuzeboc**
Add additional DDS vendors to the snap.

This will fix https://github.com/facontidavide/PlotJuggler/issues/752

Since the snap is isolated, additional DDS vendors must be added to the snap itself.

### CODE REVIEW

**Comment by facontidavide** [comment]
question: how will ROS2 inside the snap select a certain vendor over the others?

**Comment by Guillaumebeuzeboc** [comment]
> question: how will ROS2 inside the snap select a certain vendor over the others?

I checked using the environment variable (`RMW_IMPLEMENTATION`) as described in [this documentation](https://docs.ros.org/en/foxy/How-To-Guides/Working-with-multiple-RMW-implementations.html).

Now that you are asking, I wonder if it would be nicer to offer the possibility to the user to set the DDS vendor for a long term.

An example would be
```
sudo snap set plotjuggler ros-rmw-implementation=rmw_connext_cpp
```
And then Plotjuggler ROS 2 would automatically use the selected vendor.

What do you think?
@artivis, any thoughts about that?

**Comment by artivis** [comment]
I would avoid introducing a PJ snap specific way of setting this parameter as this can potentially introduce confusion. E.g. what would take precedence between the snap parameter and the environment variable if both are set to different value?

**Comment by Guillaumebeuzeboc** [comment]
> I would avoid introducing a PJ snap specific way of setting this parameter as this can potentially introduce confusion. E.g. what would take precedence between the snap parameter and the environment variable if both are set to different value?

In this case, it would be the environment variable set (the parameter would be for people would always use a specific vendor and simply want to launch plotjuggler from the desktop icon).

I don't know if it would be useful to anyone, so maybe for now we can leave it with simply the environment variable.

**Comment by artivis** [comment]
Is this PR blocked by anything? Looks like it is fixing the initial issue and it's been tested by @doisyg as reported in #752

**Comment by facontidavide** [comment]
blocked by my little time to think about Plot Juggler. Thanks!!

**Comment by artivis** [comment]
Eheh sorry Davide :D 
Right back at you!

**Pull request merged**
