### PR TITLE
RosMsgParsers: add cast to be clang compatible

### LINKED ISSUE #207: PlotJuggler does not build with CLang
When building PlotJuggler with CLang, the following error occurs:
```
.../PlotJuggler/plugins/ROS/RosMsgParsers/ros_parser.cpp:123:52: error: 
      non-constant-expression cannot be narrowed from type 'size_t' (aka 'unsigned long') to
      'nonstd::span_lite::span::index_type' (aka 'long') in initializer list [-Wc++11-narrowing]
                {const_cast<uint8_t*>(msg.data()), msg.size()},
                                                   ^~~~~~~~~~
.../PlotJuggler/plugins/ROS/RosMsgParsers/ros_parser.cpp:123:52: note: insert an
      explicit cast to silence this issue
                {const_cast<uint8_t*>(msg.data()), msg.size()},
                                                   ^~~~~~~~~~
                                                   static_cast<index_type>( )
```
On GCC, this is only a warning. CLang seems to be more restrictive here.

### PR DESCRIPTION
**Pull request by timonegk**
This closes #207 by adding the requested cast.

### CODE REVIEW

**Comment by facontidavide** [comment]
thanks a lot

**Comment by meyerj** [comment]
Many thanks for this valuable tool!

Unfortunately this patch broke compilation on Ubuntu Bionic with Clang and the released version 1.3.3 of [ros_type_introspection](https://github.com/facontidavide/ros_type_introspection) in ROS melodic:

```
.../PlotJuggler/plugins/ROS/RosMsgParsers/ros_parser.cpp:123:52: error: non-constant-expression cannot be narrowed from type 'long' to 'absl::Span::size_type' (aka 'unsigned long') in initializer list [-Wc++11-narrowing]
                {const_cast<uint8_t*>(msg.data()), static_cast<long>(msg.size())},                                                                                                                                                   
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                     
.../PlotJuggler/plugins/ROS/RosMsgParsers/ros_parser.cpp:123:52: note: insert an explicit cast to silence this issue                                                                                 
                {const_cast<uint8_t*>(msg.data()), static_cast<long>(msg.size())},                                                                                                                                                   
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                                                     
                                                   static_cast<size_type>(      )                                                                                                                                                    
```

So just the opposite of what has been reported in #207 now. Obviously for the Abseil version the expected type is `unsigned long` or `absl::Span::size_type`, not `long`. Maybe casting to `const std::size_t` works in both cases, just from the error message?

**Comment by facontidavide** [comment]
Hi. 

you MUST upgrade to ros_type_introspection 2.0.2

If the problem persist, let me know

**Comment by meyerj** [comment]
> you MUST upgrade to ros_type_introspection 2.0.2

Thanks, that solved it. We were using the released version 1.3.3 of `ros_type_introspection` in the public repos, but built PlotJuggler from source. I assume waiting until 2.0.2 hits the public repos or installing it manually from shadow will fix the issue.

**Pull request merged**
