### PR TITLE
Ros2 install paths

### PR DESCRIPTION
**Pull request by mlautman**
Addresses the issue raised here: https://github.com/facontidavide/PlotJuggler/issues/289

This does 3 main things:
1. It calls `ament_package()` at the end of the CMakeLists.txt to make it so that the ros2 package index can find `plotjuggler`
2. It moves the built executables into `lib/plotjuggler/` instead of `bin` so that `ros2 run` can find them. 
3. It also moves the libraries into the executable folder (`$CATKIN_WS/install/plotjuggler/lib/plotjuggler/`) so that they can be found by PlotJuggler. Ideally, they would be in the standard library location (`$CATKIN_WS/install/plotjuggler/lib/`) but then they cannot be found by PlotJuggler because it only looks in its current directory and in a system install dir.

`tree $CATKIN_WS/install/plotjuggler` should now produce the (mostly) standard directory structure:
```
plotjuggler/
├── lib
│   └── plotjuggler
│       ├── libDataLoadCSV.so
│       ├── libDataLoadROS2.so
│       ├── libDataLoadULog.so
│       ├── libDataStreamROS2.so
│       ├── libDataStreamSample.so
│       └── PlotJuggler
└── share
    ├── ament_index
    │   └── resource_index
    │       ├── package_run_dependencies
    │       │   └── plotjuggler
    │       ├── packages
    │       │   └── plotjuggler
    │       └── parent_prefix_path
    │           └── plotjuggler
    ├── applications
    │   └── PlotJuggler.desktop
    ├── colcon-core
    │   └── packages
    │       └── plotjuggler
    ├── icons
    │   └── plotjuggler.svg
    └── plotjuggler
        ├── cmake
        │   ├── plotjugglerConfig.cmake
        │   └── plotjugglerConfig-version.cmake
        ├── environment
        │   ├── ament_prefix_path.dsv
        │   ├── ament_prefix_path.sh
        │   ├── path.dsv
        │   └── path.sh
        ├── hook
        │   ├── cmake_prefix_path.dsv
        │   ├── cmake_prefix_path.ps1
        │   └── cmake_prefix_path.sh
        ├── local_setup.bash
        ├── local_setup.dsv
        ├── local_setup.sh
        ├── local_setup.zsh
        ├── package.bash
        ├── package.dsv
        ├── package.ps1
        ├── package.sh
        ├── package.xml
        └── package.zsh
```

### CODE REVIEW

**Comment by mlautman** [comment]
@facontidavide

**Comment by mlautman** [comment]
edit: added a fix for #291

**Comment by facontidavide** [comment]
hi @mlautman 

first of all, thanks a LOT

the ros2 branch is obsolete, you should merge againg **master**, not ros2

**Comment by facontidavide** [comment]
merged individual changes. thanks for contributing

**Pull request closed without merging**
