### PR TITLE
Added ZeroMQ and updated docs

### PR DESCRIPTION
**Pull request by ubaldot**
Necessary work to build from source code on macos 14.2.1 (and most likely newer and older). 
This PR also solves https://github.com/facontidavide/PlotJuggler/issues/897

### CODE REVIEW

**Comment by facontidavide** [comment]
this PR caused a regression in Windows (see CI).

Please provide a solution or I will revert it

**Comment by ubaldot** [comment]
I googled the error and it it seems that there is PkgConfig for windows. 
A possible solution could be to install the following package: 

`choco install pkgconfiglite`

But I have no Windows machine, so I cannot test if it actually solve. 
Would that be possible to run this solution over some GitHub actions Windows runner and see if it solve the issue?

**Comment by facontidavide** [comment]
Yes, you should be able to run the CI in your own fork.

Nut please enable this in CMakeLists only when running in Macos, if you can.

**Comment by ubaldot** [comment]
I managed to run the build locally, I fixed the build for Windows but that opened another problem with macos issue. This change is to fix the build for arm64 architecture, but the runner running the github workflow seems to use the x86 architecture only. 

However, I found this [recent blog article](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) but it is not super clear to me how it should work. 

I'll try to investigate more...

**Comment by ubaldot** [comment]
UPDATE: Since I managed to build PlotJuggler locally, it seems that something has changed either in PlotJuggler source code or in protobuf.

The error that I get around 93% of the build is the following:

```
/Users/runner/work/PlotJuggler/PlotJuggler/plotjuggler_plugins/ParserProtobuf/error_collectors.h:13:45: error: only virtual member functions can be marked 'override'
                const std::string& message) override;
                                            ^~~~~~~~
/Users/runner/work/PlotJuggler/PlotJuggler/plotjuggler_plugins/ParserProtobuf/error_collectors.h:16:47: error: only virtual member functions can be marked 'override'
                  const std::string& message) override;
                                              ^~~~~~~~
/Users/runner/work/PlotJuggler/PlotJuggler/plotjuggler_plugins/ParserProtobuf/error_collectors.h:31:45: error: only virtual member functions can be marked 'override'
                const std::string& message) override;
                                            ^~~~~~~~
/Users/runner/work/PlotJuggler/PlotJuggler/plotjuggler_plugins/ParserProtobuf/error_collectors.h:34:47: error: only virtual member functions can be marked 'override'
                  const std::string& message) override;
```

which seems that there is a `virtual` less or an `override` more and it seems an easy fix in the source code. However,  take that with a grain of salt since I am not a C++ guy. 

In-fact, I don't know if the issue is on protobuf or on PlotJuggler side, either way I don't dare to change the code by adding `virtual` or by removing `override`. By googling a bit, it seems there may be some relation with abseil but, again, I cannot say.

**Pull request merged**
