### PR TITLE
Add mac compilation section

### PR DESCRIPTION
**Pull request by bonkuraps**
Hey!

I've added Mac compilation section and fixed some minor typos.

### CODE REVIEW

**Comment by facontidavide** [comment]
since we are doing this, maybe we should also add these dependencies:

https://github.com/facontidavide/PlotJuggler/blob/main/conanfile.txt#L2-L5

Can you please modify your PR to add them?

**Comment by bonkuraps** [comment]
> since we are doing this, maybe we should also add these dependencies:
> 
> https://github.com/facontidavide/PlotJuggler/blob/main/conanfile.txt#L2-L5
> 
> Can you please modify your PR to add them?

Done!

**Comment by facontidavide** [comment]
Thanks

**Comment by mengchaoheng** [comment]
```Console
[ 99%] Built target DataStreamSample
[ 99%] Built target DataStreamZMQ
[ 99%] Built target DataStreamWebSocket
2 warnings generated.
1 warning generated.
2 warnings generated.
[ 99%] Linking CXX shared library ../../bin/libDataStreamMQTT_Mosquitto.dylib
[ 99%] Built target DataStreamMQTT_Mosquitto
2 warnings generated.
/Users/mch/Proj/plotjuggler_ws/src/PlotJuggler/plotjuggler_app/mainwindow.cpp:2015:65: warning: 'SkipEmptyParts' is deprecated [-Wdeprecated-declarations]
    info.selected_datasources = topics_list.split(";", QString::SkipEmptyParts);
                                                                ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qstring.h:605:24: note: 'SkipEmptyParts' has been explicitly marked deprecated here
        SkipEmptyParts Q_DECL_ENUMERATOR_DEPRECATED
                       ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qcompilerdetection.h:1160:40: note: expanded from macro 'Q_DECL_ENUMERATOR_DEPRECATED'
#  define Q_DECL_ENUMERATOR_DEPRECATED Q_DECL_DEPRECATED
                                       ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qcompilerdetection.h:227:45: note: expanded from macro 'Q_DECL_DEPRECATED'
#  define Q_DECL_DEPRECATED __attribute__ ((__deprecated__))
                                            ^
/Users/mch/Proj/plotjuggler_ws/src/PlotJuggler/plotjuggler_app/mainwindow.cpp:2015:45: warning: 'split' is deprecated: Use split(const QString &sep, Qt::SplitBehavior ...) variant instead [-Wdeprecated-declarations]
    info.selected_datasources = topics_list.split(";", QString::SkipEmptyParts);
                                            ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qstring.h:608:23: note: 'split' has been explicitly marked deprecated here
    Q_REQUIRED_RESULT QT_DEPRECATED_VERSION_X_5_15("Use split(const QString &sep, Qt::SplitBehavior ...) variant instead")
                      ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qglobal.h:374:45: note: expanded from macro 'QT_DEPRECATED_VERSION_X_5_15'
# define QT_DEPRECATED_VERSION_X_5_15(text) QT_DEPRECATED_X(text)
                                            ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
#  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qcompilerdetection.h:675:55: note: expanded from macro 'Q_DECL_DEPRECATED_X'
#    define Q_DECL_DEPRECATED_X(text) __attribute__ ((__deprecated__(text)))
                                                      ^
2 warnings generated.
/Users/mch/Proj/plotjuggler_ws/src/PlotJuggler/plotjuggler_app/mainwindow.cpp:2462:18: warning: 'width' is deprecated: Use QFontMetrics::horizontalAdvance [-Wdeprecated-declarations]
  int width = fm.width(timeLine->text()) + 10;
                 ^
/opt/homebrew/opt/qt@5/lib/QtGui.framework/Headers/qfontmetrics.h:105:5: note: 'width' has been explicitly marked deprecated here
    QT_DEPRECATED_X("Use QFontMetrics::horizontalAdvance")
    ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
#  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qcompilerdetection.h:675:55: note: expanded from macro 'Q_DECL_DEPRECATED_X'
#    define Q_DECL_DEPRECATED_X(text) __attribute__ ((__deprecated__(text)))
                                                      ^
[100%] Linking CXX shared library ../../bin/libDataLoadCSV.dylib
/Users/mch/Proj/plotjuggler_ws/src/PlotJuggler/plotjuggler_app/mainwindow.cpp:3133:33: warning: 'endl' is deprecated: Use Qt::endl [-Wdeprecated-declarations]
    stream << doc.toString() << endl;
                                ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qtextstream.h:293:15: note: 'endl' has been explicitly marked deprecated here
Q_CORE_EXPORT QT_DEPRECATED_VERSION_X(5, 15, "Use Qt::endl") QTextStream &endl(QTextStream &s);
              ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qglobal.h:390:53: note: expanded from macro 'QT_DEPRECATED_VERSION_X'
#define QT_DEPRECATED_VERSION_X(major, minor, text) QT_DEPRECATED_VERSION_X_##major##_##minor(text)
                                                    ^
<scratch space>:27:1: note: expanded from here
QT_DEPRECATED_VERSION_X_5_15
^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qglobal.h:374:45: note: expanded from macro 'QT_DEPRECATED_VERSION_X_5_15'
# define QT_DEPRECATED_VERSION_X_5_15(text) QT_DEPRECATED_X(text)
                                            ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
#  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                ^
/opt/homebrew/opt/qt@5/lib/QtCore.framework/Headers/qcompilerdetection.h:675:55: note: expanded from macro 'Q_DECL_DEPRECATED_X'
#    define Q_DECL_DEPRECATED_X(text) __attribute__ ((__deprecated__(text)))
                                                      ^
[100%] Built target DataLoadCSV
2 warnings generated.
2 warnings generated.
4 warnings generated.
2 warnings generated.
4 warnings generated.
[100%] Linking CXX shared library ../../bin/libToolboxLuaEditor.dylib
[100%] Built target ToolboxLuaEditor
3 warnings generated.
[100%] Linking CXX shared library ../../bin/libToolboxFFT.dylib
[100%] Built target ToolboxFFT
[100%] Linking CXX shared library ../../bin/libParserROS1.dylib
ld: warning: ignoring file /usr/local/lib/libfastcdr.1.0.8.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "eprosima::fastcdr::FastBuffer::FastBuffer(char*, unsigned long)", referenced from:
      RosMsgParser::FastCDR_Deserializer::reset() in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::readString(unsigned int&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserializeString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(bool&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(char&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(double&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(float&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(int&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
      RosMsgParser::FastCDR_Deserializer::deserializeUInt32() in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(short&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(long long&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::DEFAULT_ENDIAN", referenced from:
      RosMsgParser::FastCDR_Deserializer::reset() in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::getBufferPointer()", referenced from:
      RosMsgParser::FastCDR_Deserializer::getCurrentPtr() const in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::read_encapsulation()", referenced from:
      RosMsgParser::FastCDR_Deserializer::reset() in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::jump(unsigned long)", referenced from:
      RosMsgParser::FastCDR_Deserializer::jump(unsigned long) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::Cdr(eprosima::fastcdr::FastBuffer&, eprosima::fastcdr::Cdr::Endianness, eprosima::fastcdr::Cdr::CdrType)", referenced from:
      RosMsgParser::FastCDR_Deserializer::reset() in librosx_introspection.a(deserializer.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/libParserROS1.dylib] Error 1
make[1]: *** [plotjuggler_plugins/ParserROS/CMakeFiles/ParserROS1.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[100%] Linking CXX shared library ../../bin/libParserROS2.dylib
ld: warning: ignoring file /usr/local/lib/libfastcdr.1.0.8.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "eprosima::fastcdr::FastBuffer::FastBuffer(char*, unsigned long)", referenced from:
      RosMsgParser::FastCDR_Deserializer::reset() in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::readString(unsigned int&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserializeString(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(bool&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(char&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(double&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(float&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(int&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
      RosMsgParser::FastCDR_Deserializer::deserializeUInt32() in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(short&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::deserialize(long long&)", referenced from:
      RosMsgParser::FastCDR_Deserializer::deserialize(RosMsgParser::BuiltinType) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::DEFAULT_ENDIAN", referenced from:
      RosMsgParser::FastCDR_Deserializer::reset() in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::getBufferPointer()", referenced from:
      RosMsgParser::FastCDR_Deserializer::getCurrentPtr() const in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::read_encapsulation()", referenced from:
      RosMsgParser::FastCDR_Deserializer::reset() in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::jump(unsigned long)", referenced from:
      RosMsgParser::FastCDR_Deserializer::jump(unsigned long) in librosx_introspection.a(deserializer.cpp.o)
  "eprosima::fastcdr::Cdr::Cdr(eprosima::fastcdr::FastBuffer&, eprosima::fastcdr::Cdr::Endianness, eprosima::fastcdr::Cdr::CdrType)", referenced from:
      RosMsgParser::FastCDR_Deserializer::reset() in librosx_introspection.a(deserializer.cpp.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/libParserROS2.dylib] Error 1
make[1]: *** [plotjuggler_plugins/ParserROS/CMakeFiles/ParserROS2.dir/all] Error 2
3 warnings generated.
[100%] Linking CXX shared library ../../bin/libDataLoadMCAP.dylib
[100%] Built target DataLoadMCAP
4 warnings generated.
12 warnings generated.
[100%] Linking CXX executable ../bin/plotjuggler
[100%] Built target plotjuggler
make: *** [all] Error 2
➜  plotjuggler_ws 
```

**Comment by mengchaoheng** [comment]
if I want to use it on m1 mac, how should I do? @facontidavide

**Comment by mengchaoheng** [comment]
@bonkuraps @pgorczak can you help me ? I want to build plotjuggler on my m1 macbook pro.

**Comment by erickisos** [comment]
Hey!
@mengchaoheng let me check and I'll come back to you

**Comment by okalachev** [comment]
Got another error trying to compile on an M1 mac:

```
Undefined symbols for architecture arm64:
  "parquet::StreamReader::StreamReader(std::__1::unique_ptr<parquet::ParquetFileReader, std::__1::default_delete<parquet::ParquetFileReader> >)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::StreamReader::operator>>(signed char&)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::StreamReader::operator>>(bool&)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::StreamReader::operator>>(double&)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::StreamReader::operator>>(float&)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::StreamReader::operator>>(unsigned char&)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::StreamReader::operator>>(int&)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::StreamReader::operator>>(unsigned int&)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::StreamReader::operator>>(short&)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::StreamReader::operator>>(unsigned short&)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::StreamReader::operator>>(long long&)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::StreamReader::operator>>(unsigned long long&)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::ParquetFileReader::OpenFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, parquet::ReaderProperties const&, std::__1::shared_ptr<parquet::FileMetaData>)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::ParquetFileReader::~ParquetFileReader()", referenced from:
      DataLoadParquet::DataLoadParquet() in dataload_parquet.cpp.o
      DataLoadParquet::~DataLoadParquet() in dataload_parquet.cpp.o
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
      parquet::StreamReader::~StreamReader() in dataload_parquet.cpp.o
  "parquet::default_reader_properties()", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::operator>>(parquet::StreamReader&, parquet::EndRowType)", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::FileMetaData::num_columns() const", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::FileMetaData::schema() const", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::SchemaDescriptor::Column(int) const", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
  "parquet::ParquetFileReader::metadata() const", referenced from:
      DataLoadParquet::readDataFromFile(PJ::FileLoadInfo*, PJ::PlotDataMapRef&) in dataload_parquet.cpp.o
ld: symbol(s) not found for architecture arm64
```

**Comment by erickisos** [comment]
Hey @okalachev!

I recently cloned the repository in a new mac and just followed the instructions [in this doc](https://github.com/facontidavide/PlotJuggler/blob/main/COMPILE.md#compile-in-mac), basically:
- `brew install cmake qt@5 protobuf mosquitto zeromq zstd`
- Extra steps not mentioned in the README:
    - `echo "export CPPFLAGS=\"-I/opt/homebrew/opt/qt@5/include\"" >> $HOME/.zshrc`
    - `echo "export PKG_CONFIG_PATH=\"/opt/homebrew/opt/qt@5/lib/pkgconfig\"" >> $HOME/.zshrc`
    - `echo "export LDFLAGS=\"/opt/homebrew/opt/qt@5/lib\"" >> $HOME/.zshrc`
- `git clone https://github.com/facontidavide/PlotJuggler.git ~/plotjuggler_ws/src/PlotJuggler`
- `cd ~/plotjuggler_ws`
- `cmake -S src/PlotJuggler -B build/PlotJuggler -DCMAKE_INSTALL_PREFIX=install`
- `cmake --build build/PlotJuggler --config RelWithDebInfo --parallel --target install`

And it works.
Just in case, and probably this is something important, I don't have ROS installed at all because it's a new Mac.

Have you tried following those instructions? I will create a PR with the extra commands that are not shown there.

**Comment by okalachev** [comment]
@erickisos, I have followed the instructions, but without these extra steps. I got this error about `parquet` and was able to fix it removing a plugin with `parquet` usage. Do you want me to try to rebuild this with your additional steps?

By the way, what do you think of creating a GitHub Actions job, on a mac machine, Intel and M1, that builds this, and maybe even publishes a ready to use .dmg file? I think it won't be so difficult to do.

I like this software, for analyzing .csv files, but the requirement of manual building on a mac is extremely inconvenient.

**Comment by mengchaoheng** [comment]
I like this software, for analyzing .csv files, but the requirement of manual building on a mac is extremely inconvenient. +1

**Pull request merged**
