### PR TITLE
Distribute PlotJuggler as a Snap

### PR DESCRIPTION
**Pull request by artivis**
Add the Snapcraft configuration files to package PlotJuggler as a Snap.
This allows to package PlotJuggler together with the ROS 1 plugins as a Snap.

An example of the Snap can be found [here](https://snapcraft.io/artivis-plotjuggler). Install with:
```terminal
snap install artivis-plotjuggler --edge
```
and launch it with,
```terminal
artivis-plotjuggler.plotjuggler
```
or simply looking for 'PlotJuggler' in your application search bar.
Note that once the Snap is released under the 'plotjuggler' name, the above commands will simply be,
```terminal
snap install plotjuggler
plotjuggler
```

While the different features seem to work fine, please let me know if any anything does not work as expected.

Note, depends on https://github.com/snapcore/snapcraft/pull/3313.

More info about [Snap](https://snapcraft.io/).

Signed-off-by: artivis <deray.jeremie@gmail.com>

### CODE REVIEW

**Comment by facontidavide** [comment]
this is super awesome!

**Comment by facontidavide** [comment]
I am curious... which ROS version will be used when creating the binary?

**Comment by artivis** [comment]
> I am curious... which ROS version will be used when creating the binary?

The Snap is using [`core18`](https://github.com/facontidavide/PlotJuggler/pull/341/files#diff-56759910381a014fecfd7556dd72ddd68c747d922a5b7df2044b9ce7c552f5f5R10) which means it uses ROS Melodic.

**Comment by facontidavide** [comment]
Got this error...

```
-- Could NOT find tf (missing: tf_DIR)
-- Could not find the required component 'tf'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /root/parts/plotjuggler/install/opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "tf" with any of
  the following names:

    tfConfig.cmake
    tf-config.cmake

  Add the installation prefix of "tf" to CMAKE_PREFIX_PATH or set "tf_DIR" to
  a directory containing one of the above files.  If "tf" provides a separate
  development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:30 (find_package)
```

any clue?

**Comment by artivis** [comment]
> any clue?

Yes, that because you need the fix from snapcore/snapcraft#3313 as mentioned in the PR description. You can clone my fork of snapcraft with the said change, re-snap and install it, e.g.,
```terminal
git clone https://github.com/artivis/snapcraft.git -b feature/ros_env_var
cd snapcraft
snapcraft
snap install --dangerous --classic snapcraft-<version>.snap
```

**Comment by facontidavide** [comment]
Followed your instructions, but got:

        Issues while validating snapcraft.yaml: Additional properties are not allowed ('license' was unexpected)

**Comment by artivis** [comment]
You're getting the error while running snapcraft on the snapcraft fork right? You may be using an outdated version of snapcraft, please try updating it.

**Comment by facontidavide** [comment]
Done! Thank you again.

https://snapcraft.io/plotjuggler

**Comment by artivis** [comment]
This is great! Thank you for releasing it so rapidly :+1:

**Comment by facontidavide** [comment]
image

**Pull request merged**
