### PR TITLE
Add PoseWithCovarianceStamped parser

### PR DESCRIPTION
**Pull request by v-lopez**

### CODE REVIEW

**Comment by facontidavide** [comment]
is it me, or the header is not processed?

**Comment by facontidavide** [comment]
I have some time to work on this, but I need your help:

- How can I test it? I am not familiar with rosbridge.
- Is it ready to be merged or still work in progress?

**Comment by v-lopez** [comment]
You are right, fixed.

**Comment by facontidavide** [comment]
thanks

**Pull request merged**
