### PR TITLE
[WIP] Merge data instead of replacing it

### PR DESCRIPTION
**Pull request by TonyWelte**
This changes the way new data is added. New data with an already known name is merged with the old data (if the user wants to keep it).

This enables multiple bags recorded over the same timespan to be replayed (as "plotjuggler::rosbag1::consecutive_messages" can be merged).

It also enables to load simultaneously data recorded over a different timespan.

Relates to PlotJuggler/plotjuggler-ros-plugins#27

### CODE REVIEW

**Comment by facontidavide** [comment]
Thanks for taking the time to contribute to plotjuggler, but I am afraid that it may introduce some unexpected behavior.

I would feel more comfortable if a third option "Merge data" is available in 

          QMessageBox::question(this, tr("Warning"), tr("Do you want to remove the previously loaded data?\n"),

**Comment by TonyWelte** [comment]
I agree adding a third option is best.
Now the "Yes" button is the same as before, the "No (remove duplicates)" should be the same as the old "No" button, only the "No (merge duplicates)" adds a new behavior.

**Comment by bonkuraps** [comment]
@facontidavide would there still be a need for this feature? What do you think?

**Comment by facontidavide** [comment]
There are a number of potential drawbacks that I need to analyze. In general, there is a 80% probability that this is not a good fit for PJ, at this moment of time.

This doesn't mean I don't appreciate your contribution, but i must be mindful about the feature I merge.

**Comment by bonkuraps** [comment]
Ok, Is there anything that I might help with? Do you see any tickets that might be worth going through.

**Comment by facontidavide** [comment]
Thanks a lot for the help offer!!!
Maybe #724 , #705, #681

**Pull request closed without merging**
