### PR TITLE
Include `plotjuggler_qwt` library in install

### PR DESCRIPTION
**Pull request by zdavkeos**
This allows users to build toolboxes externally, like in this project: https://github.com/zdavkeos/balyrond

### CODE REVIEW

**Comment by facontidavide** [comment]
Fails in CI

**Comment by zdavkeos** [comment]
I will try to fix the ROS case. Hopefully this feature makes sense?

**Comment by facontidavide** [comment]
I am not fully understanding the reason behind this change. Can you elaborate?

**Comment by zdavkeos** [comment]
I am working on a project that uses PlotJuggler:
https://github.com/zdavkeos/balyrond

It builds a streaming plugin and a toolbox out-of-tree. The toolbox needs
the `plotjuggler_qwt` library for the plot widget. This pr has cmake put
`plotjuggler_qwt` into the install/ directory.

I tried several ways to accomplish this, and this came out as the easiest.

**Comment by facontidavide** [comment]
if compilation is fixed, I don't have anything against merging it

**Comment by zdavkeos** [comment]
I will close this pr until I can get ROS working in CI

**Pull request closed without merging**
