### PR TITLE
Add support for building AppImage via docker

### PR DESCRIPTION
**Pull request by bsilvereagle**
## Changes

* Revise the Dockerfile to successfully compile PlotJuggler with MQTT & ZMQ plugins
* Adds a script to compile an AppImage from within the docker environment; this will also work standalone

## Test

`docker buildx build -o . .` results a in `PlotJuggler-x86_x64.AppImage` which has been tested to have a working MQTT client via mosquitto

### CODE REVIEW

**Comment by facontidavide** [comment]
Nice, I will try it and merge it if it works as expected

**Comment by facontidavide** [comment]
Plain Ubuntu CI fails. Can you check why?

**Comment by bsilvereagle** [comment]
Does not seem relevant to the files changed in the PR.

```
[ 44%] Building CXX object 3rdparty/QCodeEditor/CMakeFiles/QCodeEditor.dir/QCodeEditor_autogen/mocs_compilation.cpp.o
In file included from /usr/include/c++/9/type_traits:35,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:45,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qtguiglobal.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/qsyntaxhighlighter.h:43,
                 from /usr/include/x86_64-linux-gnu/qt5/QtGui/QSyntaxHighlighter:1,
                 from /home/runner/work/PlotJuggler/PlotJuggler/./3rdparty/QCodeEditor/include/internal/QStyleSyntaxHighlighter.hpp:4,
                 from /home/runner/work/PlotJuggler/PlotJuggler/./3rdparty/QCodeEditor/include/QStyleSyntaxHighlighter:3,
                 from /home/runner/work/PlotJuggler/PlotJuggler/build/3rdparty/QCodeEditor/QCodeEditor_autogen/R64DXGSG6A/../../../../../3rdparty/QCodeEditor/include/internal/QCSVHighlighter.hpp:4,
                 from /home/runner/work/PlotJuggler/PlotJuggler/build/3rdparty/QCodeEditor/QCodeEditor_autogen/R64DXGSG6A/moc_QCSVHighlighter.cpp:9,
                 from /home/runner/work/PlotJuggler/PlotJuggler/build/3rdparty/QCodeEditor/QCodeEditor_autogen/mocs_compilation.cpp:2:
/usr/include/c++/9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
   32 | #error This file requires compiler and library support \
   ```

**Comment by facontidavide** [comment]
try rebasing the branch.
I will not merge this until CI passes and I don't have time to test/debug his myself

**Comment by facontidavide** [comment]
thanks!

**Pull request merged**
