### PR TITLE
ZeroMQ Topics Support.

### PR DESCRIPTION
**Pull request by bonkuraps**
ZMQ: Add topics filtering
- Add ZeroMQ topics support.
- Add ZeroMQ test publisher.
- Add requirements.txt

Issue: https://github.com/facontidavide/PlotJuggler/issues/705
---

How to test:
```bash
cd <plot_juggler_repo>/plotjuggler_plugins/DataStreamZMQ/utilities
./start_test_publisher.py --topic my_topic
```

Then in the app specify topics separated by either `;` or `,`

Screenshot 2022-09-25 at 15 39 59

### CODE REVIEW

**Comment by bonkuraps** [comment]
@facontidavide, few questions for you:
1. https://github.com/facontidavide/PlotJuggler/pull/730/files#diff-9f7a849999e617d339dbef75cc5c68fd6e230040cf1d0a6ba398898901344d19R195 <- I'm open for discussion about this one.

2. What separators should we use for filters? (right now while testing I've assume the most basic scenario aka ` ` empty whitespace)

Any other ideas?

**Comment by facontidavide** [comment]
Thanks for contributing. I will be away from the computer for the next 2 weeks. I will review this PR afterward.

I probably prefer ";" as separator

**Comment by bonkuraps** [comment]
> Thanks for contributing. I will be away from the computer for the next 2 weeks. I will review this PR afterward.
> 
> I probably prefer ";" as separator

Have a nice vacations I quess? :)

**Comment by bonkuraps** [comment]
@facontidavide bump!

**Comment by bonkuraps** [comment]
@facontidavide 
Hope you had great vacations, any input on this one? :)

**Comment by facontidavide** [comment]
Would you please provide a longer description of what this PR does, including screenshots? 
I am collapsed with work and that would save me some time :sweat_smile:

**Comment by bonkuraps** [comment]
> Would you please provide a longer description of what this PR does, including screenshots? I am collapsed with work and that would save me some time 😅

Yeah, sure! 
Will do it later today.

**Comment by bonkuraps** [comment]
@facontidavide 
I've updated the description and PR is ready for review.
I also recorded the functionality in action but the file got so big that I needed to upload it to Google Drive 😕

**Comment by bonkuraps** [comment]
explore the regex with: https://regex101.com/r/Ktgw7j/1

**Comment by bonkuraps** [comment]
@facontidavide any thoughts on this one? :)

**Comment by nealwang123** [comment]
I used the 3.6.0 installation on windows and did not find an option for zeromq to filter themes.
image

**Comment by nealwang123** [comment]
> I used the 3.6.0 installation on windows and did not find an option for zeromq to filter themes. image

Sorry, I just found out that the filter topic feature is added in version 3.6.1. I am compiling it with vcpkg.

**Pull request merged**
