### PR TITLE
Add curve and label editing along with many smaller changes.

### PR DESCRIPTION
**Pull request by mdgrogan**
I've made quite a few changes to better reflect my use case; I'm sure you will disagree with many, but you may be interested in a few. Namely, widgets for adding/editing curves and labels, increasing the number of settings that can be saved in a layout, and various bug fixes I found along the way. Hopefully some of these may be of use to somebody.

### CODE REVIEW

**Comment by facontidavide** [comment]
Nice, I will have a look !!

**Comment by facontidavide** [comment]
Great! I love when people contribute to PJ.

Can you please give me more details about the changes you made and how to check them one by one?

**Comment by facontidavide** [comment]
I think you introduced few bugs:

- CTRL-Z doesn't seem to work as expected
- it asks to remove data when there is no data

I don't kknow how to use the **Make XY** button... (can you show me a screencast?

**Comment by facontidavide** [comment]
In general, I think this PR is too big to be correctly reviewed, tested and merged. 
My suggestion is: 

1. let's agree on the feature to be merged.
2. let's prepare smaller PR
3. test and merge them individually

**Comment by mdgrogan** [comment]
I'll look into those bugs. I suppose the main feature/s would be label and curve editing dialogs. The increased number of saveable parameters for a layout may also be useful. The purpose of the **Make XY/Timeseries** button is to toggle between xy and timeseries curves while editing as illustrated below:

demo

**Comment by facontidavide** [comment]
I am not 100% convinced in terms of UX of the way the "Edit Data Source" dialog looks like. Honestly, I wan to do it differently.

I am more inclined to start adding the feature "Add/Edit labels" only.

**Comment by facontidavide** [comment]
You mentioned:

> and various bug fixes I found along the way.

PLEASE, can we address them individually? I want to fix them independently from the other changes

**Comment by mdgrogan** [comment]
Fair. I'll isolate features and bug fixes to appropriately names branches and make any pull requests from there.

**Comment by facontidavide** [comment]
Thanks, I am very grateful for your help

**Comment by facontidavide** [comment]
I decided to close this, even if I really appreciate your help, I don't want to add too many functionalities that might complicate the UI.

Cheers :)

**Pull request closed without merging**
