### PR TITLE
A small plugin creating a websocket server

### PR DESCRIPTION
**Pull request by PhilGauthier**
Hello,
I wrote a small simple plugin based on your sample.
It allow any third party application to connect to Plotjuggler using websocket and push their values.
I though it could be usefull to others.

### CODE REVIEW

**Comment by PhilGauthier** [comment]
Erf the continuous integration test fails, because it uses Qt5.2 (from Ubuntu trusty repository).
Websockets are available only from Qt5.3, I don't know if an upgrade of the target environment is planned or an option.

**Comment by JimmyDaSilva** [comment]
👍

**Comment by facontidavide** [comment]
Hi @PhilGauthier ,

congrtulation, you are the first contributor that submit a brand new plugin.
I don't have much time to review it right now, but unfortunately I can not change the minimum requirements of PlotJuggler in terms of Qt version, because I must guarantee that it will compile on trusty.

We should add to the CMakeFiles.txt a way to compile your plugin only if Qt 5.3 or higher was detected.

**Comment by PhilGauthier** [comment]
Hi @facontidavide ,
Thanks for the feedback, yes that's probably the easiest way to go for know.
I added the QT version check to the main CMakeFiles.txt as you proposed.
Cheers!

**Comment by efernandez** [comment]
After this PR was merged I'm having trouble to build PlotJuggler because it can't find `Qt5websockets` in Ubuntu 16.04.

Which debians should be installed to build it now?

I can create an issue if you prefer, but I thought I could start here, since this PR introduced this issue, and all the parts are already here.

**Comment by PhilGauthier** [comment]
@efernandez 👍 
My bad, I was on Windows and made some case errors :
https://github.com/PhilGauthier/PlotJuggler/commit/88aecc5d63a4424fb4a1e80de3d68d9fb43215ba

**Comment by efernandez** [comment]
Oh, I see. Could you create a PR, please?

I confirm it works fixing the case errors.

**Pull request merged**
